### ISSUE TITLE
/var/store doesn't exist in Raspberry Pi

### ISSUE THREAD

**Issue by mobluse** [efornara/jbit#1]
I use rpi-vfat.zip from 10-Nov-2013 21:43.

/var/store does not exist when I boot from the SD-card in Raspberry Pi. I use a 256MB SD-card.

I could compile and run hello.

On the SD-card, when viewing on it as a FAT-filesystem, testsys.c exists in /store

As it is now it's hardly useful since I can't store programs.

**Comment by efornara** [comment]
Sorry for the delay in replying. I should check my github notification settings! If you are still here...

I've just downloaded and flashed rpi-vfat.zip from sourceforge (I cannot check the time, but it's from 10-Nov-2013, so it should be the same one - it wouldn't hurt to re-download it just to be sure, though).

I've checked and unfortunately, it works for me.

If you have some experience with the shell, you might be able to troubleshoot the problem:

1) Make sure that /etc/rc.jbit looks like the one in the repository (https://github.com/efornara/jbit/blob/master/dists/buildroot/overlay/etc/rc.jbit). You can do that by typing:

```
nano /etc/rc.jbit
```

If it looks the same, you could try to redo manually what the script does, to see if you can find where the problem is.

2) Does the device exist?

```
ls -l /dev/mmcblk0p1
```

3) Can you create the mount point?

```
mkdir -p /mnt/sdcard
```

4) Can you mount the device?

```
mount -o sync /dev/mmcblk0p1 /mnt/sdcard
```

5) Can you link the store directory to /var/store?

```
ln -s /mnt/sdcard/store /var/store
```

The first command that fails should help us to find the problem.

**Comment by efornara** [comment]
The SD Card image for Raspberry Pi has been removed.

The static version of the android binary should work on any Linux-based ARM distribution, and it's now the recommended way to quickly get jbit to run on a Raspberry Pi.
